# version: '3.9'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes  # persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      ConnectionStrings__Default: "Data Source=/app/data/comments.db"
      ConnectionStrings__Redis: "redis:6379"
      ASPNETCORE_HTTP_PORTS: "5000"
      ASPNETCORE_ENVIRONMENT: "Production"
      # ASPNETCORE_URLS: "http://+:5000"
    ports:
      - "5000:5000"
    volumes:
      - sqlitedata:/app/data
      - uploads:/app/wwwroot/uploads
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlitedata:
  redisdata:
  uploads: